#!/bin/bash
#set -x
###########################################################
# Validates the branch name with the following rules:     #
# 1. It starts with feature/NLNN-<4 digits>-<any message> #
# 2. Or bugfix/<JIRA_TAG>-<4 digits>-<any message>        #
###########################################################

source .githooks/config.sh
local_branch="$(git rev-parse --abbrev-ref HEAD)"

# valid_branch_regex="^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"
valid_branch_regex="^(main|qa|test|dev|${BRANCH_PREFIXES}\/${JIRA_TAG}-[0-9]+-[A-Za-z0-9-]+|dependabot/.*)$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

exit 0
