#!/bin/bash
#set -x
############################################################
# Prepends <JIRA_TAG>-<issue number> to the commit message #
############################################################

source .githooks/config.sh
ISSUE_NUMBER_REGEX="${BRANCH_PREFIXES}\/${JIRA_TAG}-([0-9]+)"
COMMIT_MSG=$(cat $1)

if [[ $(git branch --show-current) =~ $ISSUE_NUMBER_REGEX ]]; then
  ISSUE_NUMBER=$(echo ${BASH_REMATCH[2]})
  if ! [[ $COMMIT_MSG =~ "${JIRA_TAG}-${ISSUE_NUMBER} " ]]; then
    echo "${JIRA_TAG}-${ISSUE_NUMBER} ${COMMIT_MSG}" > $1
  fi
fi

exit 0
