name: "Frontend deploy"
description: "Deploys frontend component"
branding:
  icon: cloud
  color: black

inputs:
  dockerfile_path:
    required: true
    description: path to dockerfile
  docker_image_name:
    required: true
    description: docker image name

runs:
  using: "composite"
  steps:
    - name: "Docker Login"
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.DOCKER_REGISTRY_SERVER }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

    - name: "Compose Customized Docker Image"
      shell: bash
      working-directory: ${{ env.FRONTEND_PATH }}
      run: |
        echo "Image path: ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:${{ env.INFORMATIONAL_VERSION }}"
        docker build . -f ${{ inputs.dockerfile_path }} -t ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:${{ env.INFORMATIONAL_VERSION }} -t ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:latest --build-arg VERSION=${{ env.VERSION }} --build-arg INFORMATIONAL_VERSION=${{ env.INFORMATIONAL_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:${{ env.INFORMATIONAL_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:latest

    - name: "Create or update deploy results PR comment"
      uses: im-open/update-pr-comment@v1.1.3
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      with:
        github-token: ${{ env.GH_TOKEN }}
        comment-identifier: "${{ inputs.base_name }}-deploy-results"
        comment-content: "🚀 Deployed with tag: ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:${{ env.INFORMATIONAL_VERSION }}"

    - name: Annotate deploy results
      shell: bash
      run: 'echo "🚀 Deployed with tag: ${{ env.DOCKER_REGISTRY_SERVER }}/${{ inputs.docker_image_name }}:${{ env.INFORMATIONAL_VERSION }}"'
