name: "Auto Author Assign"

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: toshimaru/auto-author-assign@fc10a9afdff733c0673a8ddf7771bede1a06f0bf # v2.1.2
