name: "Automatically update dotnet lockfiles in dependabot PRs"

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

jobs:
  update-lockfiles:
    uses: hwinther/reusable-workflows/.github/workflows/dependabot-update-dotnet-lockfiles.yml@f65228ea4276b3ff26409146ccd1191c728c811a # v1.65.0
    permissions:
      contents: read
    with:
      solution_path: src/backend
      solution_name: Backend.slnx
      dotnet_version: 10.0.x
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
