name: "Release Drafter"

on:
  workflow_dispatch:
  # push: # Disabled for now
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  # # required for autolabeler
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # used by GitVersion to find the most recent tag outside of this branch
          persist-credentials: false

      - name: Get version
        uses: reecetech/version-increment@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        id: version
        with:
          scheme: semver
          increment: patch

      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          version: ${{ steps.version.outputs.current-version }}
          # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
