name: "Release Drafter"

on:
  workflow_dispatch:
  # push: # Disabled for now
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  # # required for autolabeler
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # used by GitVersion to find the most recent tag outside of this branch
          persist-credentials: false

      - name: Get version
        uses: reecetech/version-increment@a29aa752dc3b8118a2dc2ed93faf0e95a73a9c7e # 2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch

      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        with:
          version: ${{ steps.version.outputs.current-version }}
          # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
