name: Terraform - publish rover visualization docker image to ghcr repo

on:
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the docker image
        run: |
          cd .github/actions/rover-terraform-action
          docker build . -t ghcr.io/hwinther/test-rover:latest -f Inner.Dockerfile
          # docker run ghcr.io/hwinther/test-rover:latest
          docker push ghcr.io/hwinther/test-rover:latest
